services:
  - type: web
    name: stock-prediction-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: MODEL_PATH
        value: stock_price_lstm_model.h5
      - key: SCALER_FEATURES_PATH
        value: scaler_features.pkl
      - key: SCALER_TARGET_PATH
        value: scaler_target.pkl